image: node:14-alpine

stages:
  - lint

eslint:
  stage: lint
  script:
    - yarn install
    - yarn lint:ci
  cache:
    paths:
      - node_modules/
      - yarn.lock
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

