version: '3.6'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:latest
    ports:
      - 6379:6379